/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author matth
 */
public class CreateUserPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public CreateUserPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        CreateUserButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        WeightLabel = new javax.swing.JLabel();
        IncorrectLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        WeightTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UsernameLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        UsernameLabel.setText("Username:");

        PasswordField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        PasswordField.setToolTipText("");

        PasswordLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        PasswordLabel.setText("Password:");

        CreateUserButton.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        CreateUserButton.setText("Create User");
        CreateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserButtonActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        NameLabel.setText("Name:");

        AgeLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        AgeLabel.setText("Age:");

        WeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        WeightLabel.setText("Weight:");

        IncorrectLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        IncorrectLabel.setForeground(new java.awt.Color(255, 0, 0));
        IncorrectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IncorrectLabel.setText("   ");

        UsernameTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        NameTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        AgeTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        WeightTextField.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordLabel)
                            .addComponent(NameLabel)
                            .addComponent(WeightLabel)
                            .addComponent(AgeLabel)
                            .addComponent(UsernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameTextField)
                            .addComponent(NameTextField)
                            .addComponent(WeightTextField)
                            .addComponent(PasswordField)
                            .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CreateUserButton)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IncorrectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeightLabel)
                    .addComponent(WeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(IncorrectLabel)
                .addGap(7, 7, 7)
                .addComponent(CreateUserButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserButtonActionPerformed
        if(UsernameTextField.getText().trim().isEmpty()){
            IncorrectLabel.setText("Must Have Username");
        }else if((new String(PasswordField.getPassword())).trim().isEmpty()){
            IncorrectLabel.setText("Must Have Password");
        }else if(NameTextField.getText().trim().isEmpty()){
            IncorrectLabel.setText("Must Have Name");
        }else{
            try{
                if((Main.CURRENT_USER=
                        Queries.createNewUser(UsernameTextField.getText().trim(),
                                (new String(PasswordField.getPassword())).trim(),
                                NameTextField.getText().trim(), 
                                Double.parseDouble(WeightTextField.getText().trim()),
                                Integer.parseInt(AgeTextField.getText().trim())))==null){
                    IncorrectLabel.setText("Invalid Username or Password. Please try a different one!");
                }else{
                    Main.main_runner= new MainPage();
                    Main.main_runner.setVisible(true);
                    this.dispose();
                }
            }catch(NumberFormatException e){
                IncorrectLabel.setText("Weight and Age must be numbers");
            }
        }
    }//GEN-LAST:event_CreateUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JButton CreateUserButton;
    private javax.swing.JLabel IncorrectLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel WeightLabel;
    private javax.swing.JTextField WeightTextField;
    // End of variables declaration//GEN-END:variables
}
